
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME:taskPulse}
    username: ${DB_USERNAME:taskpulse_user}
    password: ${DB_PASSWORD:taskPulse}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      connect-timeout: 2s

  cache:
    type: redis

app:
  security:
    jwt:
      secret: ${JWT_SECRET:+PiYEF0ztcSoQ1mBpzsNXBmtHASPlsM2mS3byWqJt0g}
      expiration-ms: 90000

logging:
  level:
    org.springframework.cache: TRACE
    org.springframework.data.redis.cache: TRACE
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
