
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/${DB_NAME:taskPulse}
    username: ${DB_USERNAME:taskpulse_user}
    password: ${DB_PASSWORD:taskPulse}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

